# Generated by Django 5.2.17 on 2026-09-21 19:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import scaneats.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoOcupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=None, editable=False, null=True, unique=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('OCUPADA', 'Ocupada'), ('POSIBLEMENTE_LIBRE', 'Posiblemente libre'), ('LIBRE', 'Libre')], default='OCUPADA', max_length=20)),
                ('hora_inicio', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('detectado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('capacidad', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('region', models.JSONField(blank=True, null=True, validators=[scaneats.validators.validar_region])),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Identificación única (RF-06).', max_length=30, unique=True)),
                ('nombre', models.CharField(help_text='Nombre o alias.', max_length=100)),
                ('turno', models.CharField(blank=True, choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], max_length=10)),
                ('prenda_tipo', models.CharField(blank=True, choices=[('DELANTAL', 'Delantal'), ('CAMISETA', 'Camiseta'), ('CAMISA', 'Camisa'), ('CHALECO', 'Chaleco'), ('GORRA', 'Gorra'), ('OTRO', 'Otro')], max_length=10)),
                ('prenda_color', models.CharField(blank=True, choices=[('ROJO', 'Rojo'), ('NARANJA', 'Naranja'), ('AMARILLO', 'Amarillo'), ('VERDE', 'Verde'), ('AZUL', 'Azul'), ('MORADO', 'Morado'), ('ROSADO', 'Rosado'), ('NEGRO', 'Negro'), ('BLANCO', 'Blanco'), ('GRIS', 'Gris')], max_length=10)),
                ('activo', models.BooleanField(default=True, help_text='False = dado de baja (conserva su historial).')),
            ],
            options={
                'verbose_name_plural': 'personal',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('es_exclusion', models.BooleanField(default=False, help_text='Zona de exclusión (caja): no se monitorea por privacidad (RF-15).')),
                ('region', models.JSONField(blank=True, help_text='Polígono normalizado [[x, y], ...] usado por el microservicio de visión.', null=True, validators=[scaneats.validators.validar_region])),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EventoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=None, editable=False, null=True, unique=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('hora', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metodo_identificacion', models.CharField(blank=True, choices=[('VESTIMENTA', 'Vestimenta (principal)'), ('COMPORTAMIENTO', 'Comportamiento (respaldo)')], max_length=15)),
                ('confianza', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='scaneats.eventoocupacion')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='scaneats.personal')),
            ],
            options={
                'ordering': ['hora'],
            },
        ),
        migrations.CreateModel(
            name='FusionMesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=None, editable=False, null=True, unique=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('hora_evento', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('ocupaciones', models.ManyToManyField(blank=True, related_name='fusiones', to='scaneats.eventoocupacion')),
                ('mesas', models.ManyToManyField(related_name='fusiones', to='scaneats.mesa')),
            ],
            options={
                'verbose_name_plural': 'fusiones de mesas',
                'ordering': ['-hora_evento'],
            },
        ),
        migrations.AddField(
            model_name='eventoocupacion',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocupaciones', to='scaneats.mesa'),
        ),
        migrations.CreateModel(
            name='ClasificacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('VESTIMENTA', 'Vestimenta (principal)'), ('COMPORTAMIENTO', 'Comportamiento (respaldo)')], max_length=15)),
                ('confianza', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('track_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scaneats.mesa')),
                ('personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificaciones', to='scaneats.personal')),
            ],
            options={
                'verbose_name_plural': 'clasificaciones de personal',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal', to='scaneats.zona'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas', to='scaneats.zona'),
        ),
        migrations.AddField(
            model_name='eventoocupacion',
            name='zona',
            field=models.ForeignKey(blank=True, help_text='Zona de la mesa al momento de la ocupación (se congela para el histórico).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocupaciones', to='scaneats.zona'),
        ),
        migrations.CreateModel(
            name='EvidenciaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(help_text='Clave del objeto en S3 (o ruta relativa en almacenamiento local).', max_length=500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Instante del evento que muestra el clip.')),
                ('duracion_s', models.FloatField(blank=True, null=True)),
                ('tamano_bytes', models.BigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(default='video/mp4', max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(db_index=True, help_text='Vence según la política de retención (RNF-03).')),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='scaneats.eventoentrega')),
                ('ocupacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='scaneats.eventoocupacion')),
                ('fusion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='scaneats.fusionmesas')),
            ],
            options={
                'verbose_name_plural': 'evidencias de video',
                'ordering': ['-timestamp'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('entrega__isnull', True), ('fusion__isnull', True), ('ocupacion__isnull', False)), models.Q(('entrega__isnull', False), ('fusion__isnull', True), ('ocupacion__isnull', True)), models.Q(('entrega__isnull', True), ('fusion__isnull', False), ('ocupacion__isnull', True)), _connector='OR'), name='evidencia_referencia_a_un_solo_evento')],
            },
        ),
        migrations.AddIndex(
            model_name='eventoocupacion',
            index=models.Index(fields=['mesa', 'hora_inicio'], name='scaneats_ev_mesa_id_b3d837_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventoocupacion',
            constraint=models.UniqueConstraint(condition=models.Q(('hora_fin__isnull', True)), fields=('mesa',), name='una_ocupacion_abierta_por_mesa'),
        ),
        migrations.AddConstraint(
            model_name='eventoocupacion',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__isnull', True), ('hora_fin__gte', models.F('hora_inicio')), _connector='OR'), name='ocupacion_fin_posterior_a_inicio'),
        ),
    ]
